services:
  robot-brain:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: picar_brain
    restart: always
    network_mode: host
    volumes:
      - .:/home/tim/picar_ws
      - ~/picar_data:/root/data
    environment:
      # S3 Configuration from .env file
      - S3_BUCKET=${S3_BUCKET_NAME}
      - S3_ENDPOINT_URL=http://${S3_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - ROS_DOMAIN_ID=30
    stdin_open: true
    tty: true
